# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ main ]

  schedule:
    - cron: '0 16 * * *'
    - cron: '0 6 * * *'
    # - cron: '*/1 * * * *'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Install tesseract-ocr
      run: |
        sudo apt update
        sudo apt install -y tesseract-ocr

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r ./requirements.txt

    - name: Prepare chromedriver
      uses: nanasess/setup-chromedriver@v2

    - name: dailyMission
      env:
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
        MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
        API_KEY: ${{ secrets.API_KEY }}
      run: |
        python dailyMission.py --headless

    - name: dailyMission for USER2
      env:
        USERNAME: ${{ secrets.USERNAME1 }}
        PASSWORD: ${{ secrets.PASSWORD1 }}
        MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
        MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
        API_KEY: ${{ secrets.API_KEY }}
      run: |
        python dailyMission.py --headless
